"""initial nvd schema

Revision ID: 403288614f98
Revises: 
Create Date: 2025-07-14 06:50:43.585335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '403288614f98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpe_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpe_name', sa.Text(), nullable=False),
    sa.Column('cpe_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpe_name')
    )
    op.create_table('cve_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.Text(), nullable=False),
    sa.Column('cve_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cve_id')
    )
    op.create_table('cwe_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cwe_id', sa.Text(), nullable=False),
    sa.Column('cwe_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cwe_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cwe_data')
    op.drop_table('cve_data')
    op.drop_table('cpe_data')
    # ### end Alembic commands ###
